name: flutter_bookchat
description: Bookchat Project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  cached_network_image: ^2.2.0+1
  material_design_icons_flutter: ^4.0.5345
  google_fonts: ^2.1.0
  carousel_slider: ^4.0.0
  rflutter_alert: ^2.0.4
  url_launcher: ^6.0.10
  change_app_package_name: ^1.0.0
  line_icons: ^2.0.1
  unicons: ^2.0.1
  flutter_login: ^2.2.1
  google_sign_in: ^5.1.0
  firebase_core: ^1.6.0
  firebase_auth: ^3.1.1
  font_awesome: ^5.10.1
  flutter_vector_icons: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  dash_chat: ^1.1.16
  splashscreen: ^1.3.5
  provider: ^5.0.0
  shared_preferences: ^2.0.7
  image_picker_web: ^2.0.3+1
  dio: ^4.0.0
  image_picker: ^0.8.4+1
  numberpicker: ^2.1.1
  multi_image_picker: ^4.8.01
  flutter_secure_storage: ^4.2.1
  socket_io_client: ^2.0.0-beta.4-nullsafety.0
  video_player: ^2.2.5
  file_picker: ^4.1.6
  responsive_grid: ^2.0.0
  flutter_rating_bar: ^4.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Logo.png
    - assets/images/Frame.png
    - assets/images/icon.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages